---
author: "Ann Von Holle"
date: '`r format(Sys.time(), "%d %B, %Y")`'
header-includes:
   - \usepackage{color, booktabs, pdflscape, graphicx, float, longtable, lscape}
output:
  pdf_document:
    keep_tex: true
geometry: "left=0.5cm, right=0.5cm, top=1cm, bottom=1.5cm"
editor_options: 
  chunk_output_type: console
---

<!-- NOTE: copied this file from ../includes/scripts/paper2/bch-read-all-bf-pdfversion.Rmd -->

```{r , include=FALSE}

# classoption: landscape

knitr::opts_chunk$set(fig.width=8, fig.height=8,
                      echo=FALSE, warning=FALSE,
                      message=FALSE, 
                      results='hide',
                      comment=NA)

#knitr::opts_chunk$set(root.dir = "~GitHub/unc-dissertation-markdown-p2/includes/scripts/paper1/sitar-rev5")

#knitr::opts_knit$set(root.dir = "~/dissertation/unc-dissertation-markdown-p2/includes/scripts/paper2")
knitr::opts_knit$set(root.dir = "~/GitHub/unc-dissertation-markdown-p2/includes/scripts/paper2")


```

```{r}
require(knitr)
require(kableExtra)
```

 <!-- see https://tex.stackexchange.com/questions/84506/landscape-mode-causes-a-blankpage -->

\afterpage{
\begin{landscape}

\chapter{Graffar Index Component Description\label{appgraffar}}


```{r, results='markup'}

## Nonlinear mixed effects model fit evaluation: BIC for all evaluated models

# load the data from /paper1/sitar-rev5/tables-ms.Rmd
# for graffar indices

load(file="../paper1/sitar-rev5/graffar-info.Rdata") # table.graffar3 data frame
```


```{r, results='markup'}

kable(table.graffar3,  
        booktabs=T, 
        row.names = F,
        escape=T,
        format="latex",
      longtable=T,
      caption="Description of items used for Graffar index",
        col.names = c("Graffar item", "Scale", "n(%)")) %>%
  kable_styling(latex_options = c("HOLD_position", "striped", "scale_down",
                                  "repeat_header"),
                font_size = 9,
                stripe_color="vlg") %>%
  column_spec(1, width = "20em")

```


\end{landscape}
}